apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cinetrackr
type: Opaque
stringData:
  mongo-uri: mongodb://admin:cinetrackr123@mongodb-0.mongodb.cinetrackr.svc.cluster.local:27017/cinetrackr?authSource=admin