spring:
  datasource:
    url: jdbc:h2:mem:cinetrackr
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  cors:
    allowed-origins: http://localhost:5173